### ISSUE TITLE
this is not a hello world program

### ISSUE THREAD

**Issue by mnhrdt** [hdante/hello_wayland#4]
I object to the name and the documentation of this repository.  This is not a hello world program.

A hello world program should fit on a single file and be minimal.  This program looks more like a framework for developing wayland applications, not a minimal working example.  There are even unused macros, such as "max"!  The only useful code is hidden behind "helper" functions.

**Comment by hdante** [comment]
I don't agree with your definition of hello world.

**Comment by hdante** [comment]
Closing abandoned issue
