### ISSUE TITLE
wl-shell is deprecated

### ISSUE THREAD

**Issue by emersion** [hdante/hello_wayland#5]
wl-shell has been deprecated in the Wayland protocol.

Would you merge a PR that uses xdg-shell instead?

**Comment by hdante** [comment]
Sure

**Comment by emersion** [comment]
>I am curious, where has wl_shell been deprecated? It's part of the core protocol since version 1.0 and is supported by most desktops. When will it be removed?

It has been deprecated in the [Wayland protocol itself](https://wayland.freedesktop.org/docs/html/apa.html#protocol-spec-wl_shell). It will be removed from Sway in the near future. In practice, it's used by very few clients, which makes it hard to test.

**Comment by emersion** [comment]
@hdante By the way, I ended up rewriting the whole project from scratch for various reasons: https://github.com/emersion/hello-wayland

I'm not sure what's the best way to update this project. Want me to submit a big pull request?

**Comment by hdante** [comment]
It looks like a complete fork, so it makes more sense to just add a link to the new project
